[project]
name = "uv-zoom"
version = "0.1.0"
description = "Churn prediction project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.2",
    "pandas>=2.3.3",
    "scikit-learn==1.6.1",
    "uvicorn>=0.38.0",
]
